### ISSUE TITLE
Help in Deployment And Access

### ISSUE THREAD

**Issue by samlasar** [sstadelman/passport-ucwa#1]
I've downloaded this code and added it as a Node porject in Eclipse IDE.Could you please help me in deploying it in node server and also I want to know, how do I pass my SKYPE business credentials and login. Please help. Please treat this on High Priority. Thank you in Advance.

**Comment by sstadelman** [comment]
I am not maintaining this actively at the moment.  But, the setup is to configure Passport.js in your node application, and `require` this project as a Passport `Strategy`.  

To authenticate, supply Authorization header with Base64 username/password, and the user email address as the POST request body.

**Comment by samlasar** [comment]
Passport.js file is not in this repository. Do I need to create new?

**Comment by sstadelman** [comment]
please investigate http://passportjs.org
